---
on:
  schedule:
    - cron: '0 9-17 * * 1-5'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5
        with:
          python-version: '3.10'

      - name: Update the site
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          pip install -r scripts/requirements.txt
          python scripts/main.py

      - name: Publish
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add app/views/dc22
          git diff-index --quiet HEAD || git commit -m 'Update the site'
          git push
